<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctt/player_result.proto

namespace App\Grpc\Ctt;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ctt.GetPlayerResultResponse</code>
 */
class GetPlayerResultResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ctt.Result result = 1;</code>
     */
    protected $result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Grpc\Ctt\Result $result
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\Ctt\GPBMetadata\PlayerResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ctt.Result result = 1;</code>
     * @return \App\Grpc\Ctt\Result|null
     */
    public function getResult()
    {
        return $this->result;
    }

    public function hasResult()
    {
        return isset($this->result);
    }

    public function clearResult()
    {
        unset($this->result);
    }

    /**
     * Generated from protobuf field <code>.ctt.Result result = 1;</code>
     * @param \App\Grpc\Ctt\Result $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \App\Grpc\Ctt\Result::class);
        $this->result = $var;

        return $this;
    }

}

