<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctt/player_result.proto

namespace App\Grpc\Ctt;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ctt.GetPlayerResultRequest</code>
 */
class GetPlayerResultRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 license = 1;</code>
     */
    protected $license = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $license
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\Ctt\GPBMetadata\PlayerResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 license = 1;</code>
     * @return int
     */
    public function getLicense()
    {
        return $this->license;
    }

    /**
     * Generated from protobuf field <code>int32 license = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLicense($var)
    {
        GPBUtil::checkInt32($var);
        $this->license = $var;

        return $this;
    }

}

