version: "3.9"

name: myhomehub-dev.

services:

  traefik:
    image: traefik:v3.0
    container_name: myhomehub_traefik
    command:
      - "--configFile=/traefik/traefik.yml"
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik:/traefik

    
    labels:
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.traefik.rule=Host(`traefik.myhome.hub.test`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - myhomehub_network
  nginx:
    image: nginx:stable-alpine
    container_name: myhomehub_nginx
    depends_on:
      - laravel
    volumes:
      - ../../laravel:/var/www:ro
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`myhome.hub.test`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls=true"
    networks:
      - myhomehub_network
  
  laravel:
    build:
      context: ../
      dockerfile: laravel/Dockerfile
    container_name: myhomehub_laravel
    volumes:
      - ../../laravel:/var/www
      - ../../.env:/var/www/.env:ro
    depends_on:
      - mysql
    expose:
      - "9000"      
    networks:
      - myhomehub_network

  mysql:
    image: mysql:8.0
    container_name: myhomehub_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${CONTAINER_MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    networks:
      - myhomehub_network

  mailhog:
    image: mailhog/mailhog
    container_name: myhomehub_mailhog
    ports:
      - "8025:8025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.myhome.hub.test`)"
      - "traefik.http.routers.mailhog.entrypoints=websecure"
      - "traefik.http.routers.mailhog.tls=true"
    networks:
      - myhomehub_network

networks:
  myhomehub_network:

volumes:
  mysql_data:

