server {
    listen 80;
    server_name thiebault.be;

    root /var/www/static;
    index index.html;

    access_log /var/log/nginx/static_access.log;
    error_log  /var/log/nginx/static_error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name myhome.thiebault.be blog.thiebault.be media.thiebault.be;

    access_log /var/log/nginx/laravel_access.log;
    error_log  /var/log/nginx/laravel_error.log debug;

    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_index index.php;

        fastcgi_pass laravel:9000;

        fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
    }
}
