name: myhomehub

services:
  traefik:
    image: traefik:v2.11
    container_name: myhomehub_traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # 🔥 force HTTPS only
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      - "--certificatesresolvers.le.acme.email=webmaster@thiebault.be"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # KEEP CERTS IN VOLUMe MANAGED BY DOCKER FOR PERSISTENCE
      # ON VPS HERE /var/lib/docker/volumes/myhomehub_traefik_certs
      - traefik_certs:/letsencrypt
    networks:
      - myhomehub_network
    restart: unless-stopped

  nginx:
    image: ghcr.io/pistonman33/myhomehub-static:latest
    container_name: myhomehub_nginx
    depends_on:
      - laravel
    volumes:
      # SHARED FOLDER WEBSERVER STATIC FRONTEND FILES FOR NGINX AND LARAVEL
      # ON VPS HERE /var/lib/docker/volumes/myhomehub_laravel_public
      - laravel_public:/var/www/public:ro
      # KEEP FOLDER FOR LARAVEL STORAGE PERSISTENT AND PERMISSIONS MANAGEMENT BY DOCKER
      # ON VPS HERE /var/lib/docker/volumes/myhomehub_laravel_storage
      - laravel_storage:/var/www/storage/app
    labels:
      - "traefik.enable=true"

      # 🔥 Laravel routes
      - "traefik.http.routers.laravel.rule=Host(`myhome.thiebault.be`) || Host(`blog.thiebault.be`) || Host(`media.thiebault.be`)"
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls=true"
      - "traefik.http.routers.laravel.tls.certresolver=le"

      # 🔥 Static
      - "traefik.http.routers.static.rule=Host(`thiebault.be`)"
      - "traefik.http.routers.static.entrypoints=websecure"
      - "traefik.http.routers.static.tls=true"
      - "traefik.http.routers.static.tls.certresolver=le"

      # 🔥 WWW redirect to non-www
      - "traefik.http.routers.www-static.rule=Host(`www.thiebault.be`)"
      - "traefik.http.routers.www-static.entrypoints=websecure"
      - "traefik.http.routers.www-static.tls=true"
      - "traefik.http.routers.www-static.tls.certresolver=le"
      - "traefik.http.routers.www-static.middlewares=redirect-www-to-nonwww"

      - "traefik.http.middlewares.redirect-www-to-nonwww.redirectregex.regex=^https://www\\.thiebault\\.be(.*)"
      - "traefik.http.middlewares.redirect-www-to-nonwww.redirectregex.replacement=https://thiebault.be$1"
      - "traefik.http.middlewares.redirect-www-to-nonwww.redirectregex.permanent=true"

      # 🔥 IMPORTANT port
      - "traefik.http.services.laravel.loadbalancer.server.port=80"
    networks:
      - myhomehub_network
    restart: unless-stopped

  laravel:
    image: ghcr.io/pistonman33/myhomehub-laravel:latest
    container_name: myhomehub_laravel
    volumes:
      # SHARED FOLDER WEBSERVER STATIC FRONTEND FILES FOR NGINX AND LARAVEL
      # ON VPS HERE /var/lib/docker/volumes/myhomehub_laravel_public
      - laravel_public:/var/www/public
      # KEEP FOLDER FOR LARAVEL STORAGE PERSISTENT AND PERMISSIONS MANAGEMENT BY DOCKER
      # ON VPS HERE /var/lib/docker/volumes/myhomehub_laravel_storage
      - laravel_storage:/var/www/storage/app
      # KEEP FOLDER FOR LARAVEL STORAGE PERSISTENT AND PERMISSIONS MANAGEMENT BY DOCKER
      # SHARED LOGS SCHEDULER BETWEEN LARAVEL AND SCHEDULER
      - laravel_logs:/var/www/storage/logs
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - myhomehub_network
    restart: unless-stopped
    command: php-fpm

  scheduler:
    image: ghcr.io/pistonman33/myhomehub-laravel:latest
    container_name: myhomehub_scheduler
    volumes:
      # KEEP BACKUPS AND IMAGES STORE ON THE FOLDER OUTSIDE THE CONTAINER
      # ON VPS HERE /var/lib/docker/volumes/myhomehub_laravel_storage
      - laravel_storage:/var/www/storage/app
      # SHARED LOGS BETWEEN LARAVEL AND SCHEDULER
      - laravel_logs:/var/www/storage/logs
    env_file:
      - .env
    command: >-
      sh -c "mkdir -p /var/www/storage/logs &&
        chown www-data:www-data /var/www/storage/logs &&
        php artisan schedule:work --verbose"
    networks:
      - myhomehub_network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: myhomehub_mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${CONTAINER_MYSQL_ROOT_PASSWORD}
    # ON VPS HERE /var/lib/docker/volumes/myhomehub_mysql_data
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - myhomehub_network
    restart: unless-stopped

networks:
  myhomehub_network:

volumes:
  mysql_data:
  traefik_certs:
  laravel_public:
  laravel_storage:
  laravel_logs:
