FROM ghcr.io/pistonman33/myhomehub:latest

# Switch on root to install require-dev
USER root

# Install dev dependencies for Laravel (testing and code quality)
RUN composer install --prefer-dist --no-interaction --ignore-platform-reqs

# Copy the testing environment file
COPY laravel/.env.testing .env

# Fix permissions for www-data
RUN chown -R www-data:www-data /var/www/vendor /var/www/storage /var/www/bootstrap/cache

# Switch back
USER www-data
WORKDIR /var/www