entryPoints:
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

  file:
    filename: /traefik/dynamic.yml
    watch: true

api:
  dashboard: true
log:
  level: DEBUG
