name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
          -t ghcr.io/pistonman33/myhomehub:latest \
          -f docker/laravel/Dockerfile.prod .

      - name: Push Docker image
        run: |
          docker push ghcr.io/pistonman33/myhomehub:latest

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CI image
        run: |
          docker build \
            -t myhomehub-ci \
            -f docker/laravel/Dockerfile.prod .

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e APP_ENV=testing \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=host.docker.internal \
            -e DB_PORT=3306 \
            -e DB_DATABASE=myhomehub_test \
            -e DB_USERNAME=root \
            -e DB_PASSWORD=root \
            -e COMPOSER_ALLOW_SUPERUSER=1
            myhomehub-ci \
            sh -c "composer install && php artisan test --parallel"

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/myhomehub
            docker compose pull
            docker compose up -d
            docker system prune -f
